python util/graph_generator.py 3 data/SMART_SEARCH_BC.csv data/SMART_SEARCH_WC.csv data/SMART_SEARCH_RC.csv "Smart Search Algorithm Case Comparison"
python util/graph_generator.py 3 data/SWEEP_LINE_BC.csv data/SWEEP_LINE_WC.csv data/SWEEP_LINE_RC.csv "Sweep Line Algorithm Case Comparison"
python util/graph_generator.py 3 data/BF_BC.csv data/BF_WC.csv data/BF_RC.csv "Brute Force Algorithm Case Comparison"
python util/graph_generator.py 3 data/SMART_SEARCH_BC.csv data/SWEEP_LINE_BC.csv data/BF_BC.csv "Brute Force vs Smart Search vs Sweep Line Algorithm Best Case"
python util/graph_generator.py 3 data/SMART_SEARCH_WC.csv data/SWEEP_LINE_WC.csv data/BF_WC.csv "Brute Force vs Smart Search vs Sweep Line Algorithm Worst Case"
python util/graph_generator.py 3 data/SMART_SEARCH_RC.csv data/SWEEP_LINE_RC.csv data/BF_RC.csv "Brute Force vs Smart Search vs Sweep Line Algorithm Random Case"